-- MySQL Script generated by MySQL Workbench
-- Tue Sep  8 23:02:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema awlog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema awlog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `awlog` DEFAULT CHARACTER SET utf8 ;
USE `awlog` ;

-- -----------------------------------------------------
-- Table `awlog`.`awlog_logger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `awlog`.`awlog_logger` ;

CREATE TABLE IF NOT EXISTS `awlog`.`awlog_logger` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `creation_date` TIMESTAMP NOT NULL,
  `host` VARCHAR(100) NOT NULL,
  `origin` VARCHAR(100) NOT NULL,
  `details` TEXT NOT NULL,
  `stacktrace` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awlog`.`awlog_hashtag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `awlog`.`awlog_hashtag` ;

CREATE TABLE IF NOT EXISTS `awlog`.`awlog_hashtag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `description_UNIQUE` (`description` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awlog`.`awlog_logger_hashtag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `awlog`.`awlog_logger_hashtag` ;

CREATE TABLE IF NOT EXISTS `awlog`.`awlog_logger_hashtag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `log_id` INT NOT NULL,
  `hastag_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_idx_loggerhasstag_hastag` (`hastag_id` ASC) VISIBLE,
  INDEX `fk_idx_loggerhastag_logger` (`log_id` ASC) VISIBLE,
  CONSTRAINT `fk_loggerhastag_hastag`
    FOREIGN KEY (`hastag_id`)
    REFERENCES `awlog`.`awlog_hashtag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loggerhastag_logger`
    FOREIGN KEY (`log_id`)
    REFERENCES `awlog`.`awlog_logger` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
